name: CodingChallenge
version: ${project.version}
main: dev.baqel.codingchallenge.CodingChallenge
authors: [Baqel]
description: Coding challenge
commands:
  suggest:
    usage: "/suggest <message>"
  view:
    usage: "/view <UUID, ID, -a> (page)"
